version: '3.1'

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=redis
      - POSTGRES_USER=redis
      - POSTGRES_DB=redis